Improve Forum and Post UI
meili-epfl/Meili pull request #283
Opened 2021-05-26 13:54 UTC by Bwananah

This PR improves the Forum and Post UI by : 
- Placing the upvote and downvote buttons so that they are more reachable and intuitive 
- Moving the add Post button so it is not in an awkward spot
- Removing the default photo from Posts
- Showing photos in the forum preview

2021-05-28 13:11 UTC, aman3014 requested changes
Thanks for this feature, it makes the forum experience much better!

I just had a couple of refactoring changes to ask before approving.

Also, I think it could be nice to resize the images in the forum. It can be very simply done using Picasso by inserting `resize` between `load` and `into`. What do you think?

2021-05-28 13:11 UTC, aman3014 commented on app/src/main/java/com/github/epfl/meili/posts/PostListRecyclerAdapter.kt
> +            }
You can use the ImageSetter utility for this

2021-05-28 13:11 UTC, aman3014 commented on app/src/main/java/com/github/epfl/meili/posts/PostActivity.kt
> +        }
Same

2021-05-28 13:11 UTC, aman3014 commented on app/src/main/java/com/github/epfl/meili/posts/forum/ForumActivity.kt
> +            executor.execute { compressAndUploadToFirebase("images/forum/${post.postId()}", bitmap!!) }
We should store this path as a const val (since it will be easier to change and appears multiple times)

2021-05-28 13:11 UTC, aman3014 commented on app/src/main/res/layout/activity_forum.xml
> +                    android:theme="@style/Theme.Meili.button" />
Cirrus suggests that the cancel button should always be on the left and the submit on the right.

2021-05-30 08:17 UTC, MarcelTorne requested changes
Thanks for this improvement Ewan! Would it be possible to add some tests to increase code coverage?

2021-05-30 12:02 UTC, Bwananah commented
> 
> 
> Thanks for this feature, it makes the forum experience much better!
> 
> I just had a couple of refactoring changes to ask before approving.
> 
> Also, I think it could be nice to resize the images in the forum. It can be very simply done using Picasso by inserting `resize` between `load` and `into`. What do you think?

Maybe in an other PR ? I think it might be difficult to make it look good and see the whole image.

2021-05-30 12:16 UTC, Bwananah commented
> 
> 
> Thanks for this improvement Ewan! Would it be possible to add some tests to increase code coverage?

I don't know how to increase test coverage on what I have done, as it is either UI changes or setting images from the database.

2021-05-30 12:20 UTC, aman3014 approved these changes
> Maybe in an other PR ? I think it might be difficult to make it look good and see the whole image. Especially because we can have weird image sizes with the cropper.

Okay, makes sense. Thanks for fixing the other issues!

2021-05-30 12:30 UTC, MarcelTorne commented
> > Thanks for this improvement Ewan! Would it be possible to add some tests to increase code coverage?
> 
> I don't know how to increase test coverage on what I have done, as it is either UI changes or setting images from the database.

Yeah makes sense, its just that the total coverage is going down by 1% which is weird. Maybe can you try to make some test with a post with a picture? (you can load that picture from the resources, maybe even use the meili app logo to simplify or something) What do you think?

2021-05-30 13:26 UTC, aman3014 commented
I believe the coverage was only decreasing because the untested image setting code was being duplicated. Since that has been fixed now, it shouldn't be a problem IMO.

2021-05-30 14:45 UTC, MarcelTorne approved these changes
Thanks for the work Ewan!

2021-05-31 14:25 UTC, merged