Show poi name of the post in feed and myPosts
meili-epfl/Meili pull request #288
Opened 2021-05-27 16:01 UTC by dyxcooh

Display the name of POI for each post when it is viewed in my posts or feed. 
Align 'sort by' text with its spinner

2021-06-02 12:56 UTC, aman3014 requested changes
Thanks for this feature! I just left a couple of minor remarks.

Also, do you think you could add very simple tests in Feed, Forum, and MyPosts to assert that the poi name is shown or not shown?

2021-06-02 12:56 UTC, aman3014 commented on app/src/main/java/com/github/epfl/meili/posts/PostListRecyclerAdapter.kt
> +        private val poiName: TextView = itemView.findViewById(R.id.ppoi_name)
typo

2021-06-02 12:56 UTC, aman3014 commented on app/src/main/java/com/github/epfl/meili/posts/PostListRecyclerAdapter.kt
> +            if(showPOI){poiName.visibility=View.VISIBLE}
autoformatting

2021-06-02 20:37 UTC, dyxcooh commented
> Thanks for this feature! I just left a couple of minor remarks.
> 
> Also, do you think you could add very simple tests in Feed, Forum, and MyPosts to assert that the poi name is shown or not shown?

Since the posts are showed as postList in these activities and identified by a single id per list, I cannot access the poi name using an id and do check(matches(isDisplayed())). Do you have an idea about how to test them in mind?

2021-06-03 06:40 UTC, aman3014 commented
> Since the posts are showed as postList in these activities and identified by a single id per list, I cannot access the poi name using an id and do check(matches(isDisplayed())). Do you have an idea about how to test them in mind?

I think you can use withText instead of withId. Just be careful because it doesn't work if there are multiple matching views. So you'll need to either give different names to pois or make a test with a single poi in the list.

2021-06-03 21:17 UTC, aman3014 approved these changes

2021-06-03 21:19 UTC, tberkane approved these changes

2021-06-03 22:09 UTC, merged